WITH RECURSIVE COLONY AS(
    SELECT ID, PARENT_ID, 1 AS LEVEL
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, A.LEVEL + 1
    FROM ECOLI_DATA E
    JOIN COLONY A ON E.PARENT_ID = A.ID
)

SELECT ID
FROM COLONY
WHERE LEVEL = 3
ORDER BY ID