SELECT A.ID, FISH_NAME_INFO.FISH_NAME, A.LENGTH
FROM FISH_INFO A
JOIN FISH_NAME_INFO ON A.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
WHERE A.LENGTH = (SELECT MAX(B.LENGTH) FROM FISH_INFO B WHERE A.FISH_TYPE = B.FISH_TYPE)
ORDER BY A.ID