WITH BEST_VIEW AS (
    SELECT BOARD_ID 
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
SELECT CONCAT('/home/grep/src/', USED_GOODS_FILE.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) FILE_PATH
FROM USED_GOODS_FILE, BEST_VIEW
WHERE USED_GOODS_FILE.BOARD_ID = BEST_VIEW.BOARD_ID
ORDER BY FILE_ID DESC