WITH PYTHON AS (
    SELECT CODE P
    FROM SKILLCODES
    WHERE NAME='Python'
), FRONTEND AS (
    SELECT SUM(CODE) F
    FROM SKILLCODES
    WHERE CATEGORY='Front End'
), CSHAP AS (
    SELECT CODE C
    FROM SKILLCODES
    WHERE NAME='C#'
), GRADE AS (
    SELECT (CASE
            WHEN (SKILL_CODE & P) <> 0 AND 
                (SKILL_CODE & F) <> 0 THEN 'A'
            WHEN (SKILL_CODE & C) <> 0 THEN 'B'
            WHEN (SKILL_CODE & F) <> 0 THEN 'C'
            ELSE NULL
        END) GRADE, ID, EMAIL
    FROM DEVELOPERS, PYTHON, FRONTEND, CSHAP
)
SELECT GRADE, ID, EMAIL
FROM GRADE
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID
